# Custom Language File for Launcher Customizer

[ejs.app]
title = "Msrgirin Launcher"

[ejs.landing]
mediaGitHubURL = "http://msrgirin.kro.kr:8100/"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/62t2cSSN32"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "만수르서버에 오신것을 환영합니다."
welcomeDescription = "#"
welcomeDescCTA = "#"
